'\" t
.\"     Title: echanged
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2009
.\"    Manual: Etools Manual
.\"    Source: Etools 0.1
.\"  Language: English
.\"
.TH "ECHANGED" "1" "11/13/2009" "Etools 0\&.1" "Etools Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
echanged \- list packages which own modified files
.SH "SYNOPSIS"
.sp
.nf
\fIechanged\fR [OPTIONS] [PATH]\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
Echanged lists packages (installed using portage or a compatible package manager) which own modified files\&. This is similar to equery check <pkgspec> but more suitable to get a grand overview of the changes to all packages on your system\&.
.sp
Unless PATH or \-\-protected is provided all installed packages are checked\&. By providing PATH (optionally multiple times) the search is limited to the given directories\&. Option \-\-protected limits the search to packages which own config protected files\&.
.sp
Unless the \-\-quiet is provided the modified files are listed along with the package\&. Option \-\-all on the other hand causes causes all modified files of a package to be listed not only those under the provided PATH or which are config protected\&.
.SH "OPTIONS"
.PP
\-\-version
.RS 4
Show version information and exit\&.
.RE
.PP
\-h, \-\-help
.RS 4
Show help message and exit\&.
.RE
.PP
\-q, \-\-quiet
.RS 4
Do not list files along with packages\&.
.RE
.PP
\-a, \-\-all
.RS 4
List all modified files even if not in <path> or not config protected\&.
.RE
.PP
\-p, \-\-protected
.RS 4
Only list packages which own config protected files\&.
.RE
.PP
<path>\&...
.RS 4
Only list files under these directories\&.
.RE
.SH "SEE ALSO"
.sp
\fBelone\fR(1) equery(1)
