.TH PROFILE-STACK 1 "September 24, 2009" "Etools User Manual"
.SH NAME
.PP
profile-stack - show stack of parent profiles of a portage profile
.SH SYNOPSIS
.PP
profile-stack [-h] [-v] [\f[I]profile\f[]]
.SH DESCRIPTION
.PP
profile-stack shows a stack of the parent profiles of the specified
portage profile.
PROFILE has to relative to \f[I]/usr/portage/profiles\f[] and
defaults to the active profile if omitted.
.PP
The stack starts with the requested profile and ends with the
profile which is loaded first.
Profiles in parentheses do not contain any configuration themselfs,
they only contain a \f[I]parent\f[] file.
They may contain \f[I]eapi\f[] or \f[I]ChangeLog\f[].
Profiles in angle brackets will be loaded again later.
.PP
When \f[B]-v\f[] is specified files in the profiles are also
listed; excluding \f[I]parent\f[], \f[I]eapi\f[] and
\f[I]ChangeLog\f[].
.SH OPTIONS
.TP
.B \[em]version
Show version information and exit.
.RS
.RE
.TP
.B -h, --help
Show help message and exit.
.RS
.RE
.TP
.B -v
Show contained files along with profiles.
.RS
.RE
.TP
.B <\f[I]profile\f[]>\&...
The profile for which to show the parents (defaults to active
profile).
.RS
.RE
.SH SEE ALSO
.PP
\f[B]profile.eselect\f[](5).
.SH AUTHOR
Jonas Bernoulli <jonas@bernoul.li>
